datasci4citizens/server-saude

app_saude/serializers.py, app_saude/views.py, citizens_project/urls.py
```
feat(SAU-XX): Recupera id de person ou provider
```
=> Feat/sau xx/full provider

app_saude/serializers.py, app_saude/views.py, citizens_project/urls.py
```
feat(SAU-28):  Patient Emenrgency
```
=> Merge Patients Emergency

DockerfileStaging, citizens_project/settings.py, libs/google.py
feat(sau-45): fix for 2 client ids
=> feat(sau-45): fix for 2 client ids

app_saude/management/commands/seed_concepts.py, app_saude/serializers.py, app_saude/views.py
Refatora os métodos do Diário para incluir áreas de interesses.
```
```
=> Feat/sau 53/refactor/interest area

app_saude/management/commands/seed_concepts.py, app_saude/serializers.py, app_saude/views.py
The retrieve of diaries by patient for the providers is not working
#48
=> fix(sau-48): Put provider diaries retrieve back to work

app_saude/management/commands/seed_concepts.py, app_saude/serializers.py, app_saude/views.py
=> 43 feat listar pedidos de ajuda página do acs

app_saude/management/commands/seed_concepts.py, app_saude/serializers.py, app_saude/views.py, citizens_project/urls.py
Corrige o erro de duplicação das observations
```
```
=> 52 fix get nos diarios do paciente

app_saude/serializers.py, app_saude/views.py, citizens_project/urls.py
Adiciona, remove e retorna areas de interesse marcadas como ponto de atencao, e quem marcou.
#53
=> feat(sau-53): add attention point

app_saude/management/commands/seed_concepts.py, app_saude/serializers.py, app_saude/views.py, citizens_project/urls.py
=> 55 fix deletar diario

app_saude/serializers.py, app_saude/utils/provider.py, app_saude/views.py, citizens_project/urls.py
- Fix ponto de atencao
- Name e rola no get user
#57
=> fix(sau-57): fix ponto de atencao

app_saude/views.py
=> fix(SAU): acs retrieve diary

app_saude/serializers.py, app_saude/views.py
=> chore(nojira): release

app_saude/views.py
=> fix(sau-75): userId missing in FullPerson create

app_saude/management/commands/seed_concepts.py
Adiciona interesses recomendados 
```
```
=> feat(SAU): new interest areas

citizens_project/settings.py
=> fix(SAU): revert

app_saude/serializers.py, app_saude/views.py
Salvo o json das áreas de interesse e diário como ensure_ascii=False
```
```
=> 115 fix marcar como atenção quebra o json

app_saude/management/commands/seed_domains.py
=> chore(SAU): try to reset database

app_saude/management/commands/seed_domains.py
=> chore(SAU): remove reset database code

app_saude/views.py
=> fix(sau-133): delete account for second time

app_saude/management/commands/seed_concepts.py, app_saude/serializers.py
=> Small fixes

CHANGELOG.md, app_saude/views.py
=> feat(sau-140): fix unlink and add logs
